const TOKEN = "token",
  REFRESH_TOKEN = "refreshToken",
  HTTP_OK = 200,
  HTTP_UNAUTHORIZED = 401,
  HTTP_SERVICE_UNAVAILABLE = 503

export { TOKEN, REFRESH_TOKEN, HTTP_OK, HTTP_UNAUTHORIZED, HTTP_SERVICE_UNAVAILABLE }
